services:
  - type: web
    name: vishwa-portfolio
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_FORMSPREE_ID
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        sync: false
